### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by MatthewScholefield** [andersfylling/fann#7]
Would you be able to create a release from the latest `master` for use with packaging/build utilities like Meson?

**Comment by MatthewScholefield** [comment]
@andersfylling Any update on this? Doesn't even have to have a description and would help a lot.

**Comment by andersfylling** [comment]
Sorry. I started looking into Meson, but I don't have the time sadly. However if you are familiar with this, . then please create a Pull Request to add this functionality.

It's much easier if people requiring specific features, that are familiar with these, provide a solution in stead :)

**Comment by MatthewScholefield** [comment]
Yeah, no need to do anything else. Just "Draft a new release" [right here](https://github.com/andersfylling/fann/releases)

**Comment by andersfylling** [comment]
I hope that should cover it. I only have a linux environment, so only linux 64 bit has been built for this release.

**Comment by MatthewScholefield** [comment]
Thanks, that'll do. Really only need the source tarball which GitHub auto generates.
